const routes = {
    home: '/',
    discover: '/discover',
    following: '/following',
    myVideo: '/myvideo',
    watchLater: '/watchlater',
    watched: '/watched',
    shorts: '/shorts',
    library: '/library',
    videolikes: '/videolikes',
    sports: '/sports',
    game: '/game',
    setting: '/setting',
    youtubemusic: '/music',
    youtubekids: '/kids',
    youtubeTv: '/tv',
    creatorStudio: '/creator-studio',
    history: '/history',
    help: '/help',
    feedback: '/feedback',
};
export default routes;
